Planner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('settings/', views.settings, name='settings'),
    path('about/', views.about, name='about'),
    path('plantypes/', views.PlanTypeListView.as_view(), name='plantypes'),
    path('plantype/<int:pk>/update/', views.PlanTypeUpdate.as_view(), name='plantype-update'),
    path('plantype/<int:pk>/delete/', views.PlanTypeDelete.as_view(), name='plantype-delete'),
    path('plantype/create/', views.PlanTypeCreate.as_view(), name='plantype-create'),
    path('planstatuses/', views.PlanStatusListView.as_view(), name='planstatuses'),
    path('planstatus/<int:pk>/update/', views.PlanStatusUpdate.as_view(), name='planstatus-update'),
    path('planstatus/<int:pk>/delete/', views.PlanStatusDelete.as_view(), name='planstatus-delete'),
    path('planstatus/create/', views.PlanStatusCreate.as_view(), name='planstatus-create'),
    path('trips/', views.TripListView.as_view(), name='trips'),
    path('trip/<int:pk>', views.TripDetailView.as_view(), name='trip-detail'),
    path('plan/<int:pk>', views.PlanDetailView.as_view(), name='plan-detail'),
    path('trip/create/', views.TripCreate.as_view(), name='trip-create'),
    path('trip/<int:pk>/update/', views.TripUpdate.as_view(), name='trip-update'),
    path('trip/<int:pk>/delete/', views.TripDelete.as_view(), name='trip-delete'),
    path('plan/<int:pk>/update/', views.PlanUpdate.as_view(), name='plan-update'),
    path('plan/<int:pk>/delete/', views.PlanDelete.as_view(), name='plan-delete'),
    path('budgetitem/<int:pk>/update/', views.BudgetItemUpdate.as_view(), name='budgetitem-update'),
    path('budgetitem/<int:pk>/delete/', views.BudgetItemDelete.as_view(), name='budgetitem-delete'),
    path('todo/<int:pk>/update/', views.TodoUpdate.as_view(), name='todo-update'),
    path('todo/<int:pk>/delete/', views.TodoDelete.as_view(), name='todo-delete'),
]

travelPlanner/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('planner/', include('Planner.urls')),
    path('', RedirectView.as_view(url='planner/', permanent=True)),
]

Planner/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower


class PlanType(models.Model):
    """Model representing a plan type (e.g. Flight, Hotel, Activity, etc.)."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a plan type (e.g. Flight, Hotel, Activity, etc.)"
    )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular plan type instance."""
        return reverse('plantype-update', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='plantype_name_case_insensitive_unique',
                violation_error_message = "Plan Type already exists (case insensitive match)"
            ),
        ]

class PlanStatus(models.Model):
    """Model representing a Plan Status (e.g. Idea, Booked, Canceled, etc.)"""
    name = models.CharField(max_length=200,
                            unique=True,
                            help_text="Enter the plan's status (e.g. Idea, Booked, Canceled, etc.)")

    def get_absolute_url(self):
        """Returns the url to access a particular language instance."""
        return reverse('planstatus-update', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='planstatus_name_case_insensitive_unique',
                violation_error_message = "Plan Status already exists (case insensitive match)"
            ),
        ]

class Trip(models.Model):
    """Model representing a trip."""
    destination = models.CharField(max_length=200)
    goal_date = models.DateField(null=True, blank=True)
    completed_date = models.DateField(null=True, blank=True)
    notes = models.TextField(
        max_length=1000, null=True, blank=True)

    class Meta:
        ordering = ['destination']

    def get_absolute_url(self):
        """Returns the url to access a particular trip record."""
        return reverse('trip-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.destination

class Plan(models.Model):
    """Model representing a plan."""
    description = models.CharField(max_length=200)
    notes = models.TextField(
        max_length=1000, null=True, blank=True)
    status = models.ForeignKey(
        PlanStatus, on_delete=models.SET_NULL, null=True)
    type = models.ForeignKey(
        PlanType, on_delete=models.SET_NULL, null=True)
    trip = models.ForeignKey(
        Trip, on_delete=models.CASCADE)
    scheduled_start_date_time = models.DateTimeField(null=True, blank=True)
    scheduled_end_date_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['scheduled_start_date_time', 'description']

    def get_absolute_url(self):
        """Returns the url to access a particular plan record."""
        return reverse('plan-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.description

class Todo(models.Model):
    """Model representing a todo."""
    description = models.CharField(max_length=200)
    notes = models.TextField(
        max_length=1000, null=True, blank=True)
    trip = models.ForeignKey(
        Trip, on_delete=models.CASCADE)
    plan = models.ForeignKey(
        Plan, on_delete=models.CASCADE, null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    date_completed = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['due_date', 'description']

    def get_absolute_url(self):
        """Returns the url to access a particular todo record."""
        return reverse('todo-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.description

class BudgetItem(models.Model):
    """Model representing a budget item."""
    description = models.CharField(max_length=200)
    notes = models.TextField(
        max_length=1000, null=True, blank=True)
    trip = models.ForeignKey(
        Trip, on_delete=models.CASCADE)
    plan = models.ForeignKey(
        Plan, on_delete=models.CASCADE, null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    amount = models.DecimalField(max_digits=7, decimal_places=2)

    ITEM_TYPES = (
        ('es', 'Estimated'),
        ('ac', 'Actual'),
        ('ex', 'Expended'),
    )

    type = models.CharField(
        max_length=2,
        choices=ITEM_TYPES,
        blank=True,
        default='es',
        help_text='Budget Item Type')

    class Meta:
        ordering = ['due_date', 'description']

    def get_absolute_url(self):
        """Returns the url to access a particular budget item record."""
        return reverse('budgetitem-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.description

Planner/views.py
from datetime import datetime

from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView

from .forms import AddTripTodoForm, AddTripBudgetItemForm, AddPlanTodoForm, AddPlanBudgetItemForm, AddTripPlanForm, \
    TripForm, UpdateTodoForm, UpdateBudgetItemForm, PlanForm, PlanStatusForm, PlanTypeForm
from .models import PlanType, PlanStatus, Plan, Trip, Todo, BudgetItem

def index(request):
    """View function for home page of site."""

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Generate counts of some of the main objects
    num_trips = Trip.objects.all().count()
    num_plans = Plan.objects.all().count()
    num_todos = Todo.objects.all().count()

    today = datetime.now().date()

    num_budget_items = BudgetItem.objects.all().count()
    past_due_todos = Todo.objects.filter(due_date__lte=today, date_completed__isnull=True).all()
    past_due_budget_items = BudgetItem.objects.filter(due_date__lte=today, type__in=['es','ac']).all()

    context = {
        'num_trips': num_trips,
        'num_plans': num_plans,
        'num_todos': num_todos,
        'num_budget_items': num_budget_items,
        'past_due_todos': past_due_todos,
        'past_due_budget_items': past_due_budget_items,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

def settings(request):

    # Render the HTML template settings.html with the data in the context variable
    return render(request, 'settings.html')

def about(request):

    # Render the HTML template about.html with the data in the context variable
    return render(request, 'about.html')

class PlanTypeListView(ListView):
    model = PlanType
    paginate_by = 10

class PlanTypeDetailView(DetailView):
    model = PlanType

class PlanStatusListView(ListView):
    model = PlanStatus
    paginate_by = 10

class PlanStatusDetailView(DetailView):
    model = PlanStatus

class TripListView(ListView):
    model = Trip
    paginate_by = 10

class TripDetailView(DetailView):
    model = Trip

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        data = {'trip': self.object}
        context["todoform"] = AddTripTodoForm(initial=data)
        context["budgetitemform"] = AddTripBudgetItemForm(initial=data)
        context["planform"] = AddTripPlanForm(initial=data)
        context["budget"] = BudgetItem.objects.filter(trip=self.object).aggregate(total=Sum('amount'))
        context["budget_expended"] = BudgetItem.objects.filter(trip=self.object, type='ex').aggregate(
            total=Sum('amount'))
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('addtype')=="todo":
            form = AddTripTodoForm(request.POST)
            if form.is_valid():
                todo = form.save()

                return HttpResponseRedirect(reverse('trip-detail', args=[todo.trip_id]))

            else:
                self.object = self.get_object()
                context = super(self).get_context_data(**kwargs)
                context['todoform'] = form
                return self.render_to_response(context=context)

        elif request.POST.get('addtype')=="budgetitem":
            form = AddTripBudgetItemForm(request.POST)
            if form.is_valid():
                budgetitem = form.save()

                return HttpResponseRedirect(reverse('trip-detail', args=[budgetitem.trip_id]))

            else:
                self.object = self.get_object()
                context = super(self).get_context_data(**kwargs)
                context['budgetitemform'] = form
                return self.render_to_response(context=context)

        elif request.POST.get('addtype') == "plan":
            form = AddTripPlanForm(request.POST)
            if form.is_valid():
                plan = form.save()

                return HttpResponseRedirect(reverse('trip-detail', args=[plan.trip_id]))

            else:
                self.object = self.get_object()
                context = super(self).get_context_data(**kwargs)
                context['planform'] = form
                return self.render_to_response(context=context)

        elif request.POST.get('completetodo'):
            todo = Todo.objects.get(pk=request.POST['completetodo'])
            todo.date_completed = datetime.now()
            todo.save()
            return HttpResponseRedirect(reverse('trip-detail', args=[todo.trip_id]))

class PlanDetailView(DetailView):
    model = Plan

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        data = {'trip': self.object.trip, 'plan': self.object}
        context["todoform"] = AddPlanTodoForm(initial=data)
        context["budgetitemform"] = AddPlanBudgetItemForm(initial=data)
        context["budget"] = BudgetItem.objects.filter(plan=self.object).aggregate(total=Sum('amount'))
        context["budget_expended"] = BudgetItem.objects.filter(plan=self.object, type='ex').aggregate(
            total=Sum('amount'))
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('addtype')=="todo":
            form = AddPlanTodoForm(request.POST)
            if form.is_valid():
                todo = form.save()

                return HttpResponseRedirect(reverse('plan-detail', args=[todo.plan_id]))

            else:
                self.object = self.get_object()
                context = super(self).get_context_data(**kwargs)
                context['todoform'] = form
                return self.render_to_response(context=context)

        elif request.POST.get('addtype')=="budgetitem":
            form = AddPlanBudgetItemForm(request.POST)
            if form.is_valid():
                budgetitem = form.save()

                return HttpResponseRedirect(reverse('plan-detail', args=[budgetitem.plan_id]))

            else:
                self.object = self.get_object()
                context = super(self).get_context_data(**kwargs)
                context['budgetitemform'] = form
                return self.render_to_response(context=context)

        elif request.POST.get('completetodo'):
            todo = Todo.objects.get(pk=request.POST['completetodo'])
            todo.date_completed = datetime.now()
            todo.save()
            return HttpResponseRedirect(reverse('plan-detail', args=[todo.plan_id]))

class TripCreate(CreateView):
    model = Trip
    form_class = TripForm

class TripUpdate(UpdateView):
    model = Trip
    form_class = TripForm

class TripDelete(DeleteView):
    model = Trip
    success_url = reverse_lazy('trips')

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("trip-delete", kwargs={"pk": self.object.pk})
            )

class PlanUpdate(UpdateView):
    model = Plan
    form_class = PlanForm

class PlanDelete(DeleteView):
    model = Plan

    def form_valid(self, form):
        try:
            trip_id = self.object.trip.pk
            self.object.delete()
            return HttpResponseRedirect(
                reverse('trip-detail', kwargs={'pk': trip_id})
            )
        except Exception as e:
            return HttpResponseRedirect(
                reverse("plan-delete", kwargs={"pk": self.object.pk})
            )

class TodoUpdate(UpdateView):
    model = Todo
    form_class = UpdateTodoForm

    def get_success_url(self):
        if self.object.plan_id:
            return reverse('plan-detail', args=[self.object.plan_id])
        else:
            return reverse('trip-detail', args=[self.object.trip_id])

class BudgetItemUpdate(UpdateView):
    model = BudgetItem
    form_class = UpdateBudgetItemForm

    def get_success_url(self):
        if self.object.plan_id:
            return reverse('plan-detail', args=[self.object.plan_id])
        else:
            return reverse('trip-detail', args=[self.object.trip_id])

class BudgetItemDelete(DeleteView):
    model = BudgetItem

    def form_valid(self, form):
        try:
            if self.object.plan_id:
                plan_id = self.object.plan.pk
                redirect_to = reverse('plan-detail', kwargs={'pk': plan_id})
            else:
                trip_id = self.object.trip.pk
                redirect_to = reverse('trip-detail', kwargs={'pk': trip_id})

            self.object.delete()
            return HttpResponseRedirect(
                redirect_to
            )
        except Exception as e:
            return HttpResponseRedirect(
                reverse("budgetitem-delete", kwargs={"pk": self.object.pk})
            )

class TodoDelete(DeleteView):
    model = Todo

    def form_valid(self, form):
        try:
            if self.object.plan_id:
                plan_id = self.object.plan.pk
                redirect_to = reverse('plan-detail', kwargs={'pk': plan_id})
            else:
                trip_id = self.object.trip.pk
                redirect_to = reverse('trip-detail', kwargs={'pk': trip_id})

            self.object.delete()
            return HttpResponseRedirect(
                redirect_to
            )
        except Exception as e:
            return HttpResponseRedirect(
                reverse("todo-delete", kwargs={"pk": self.object.pk})
            )

class PlanStatusCreate(CreateView):
    model = PlanStatus
    form_class = PlanStatusForm

Planner/templates/Planner/plan_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Plan: {{ plan }} (From Trip: {{ plan.trip }})</h1>

<p>Are you sure you want to delete the plan? The following will also be deleted:</p>

<ul>
    <li>{{ plan.todo_set.all.count }} Todos</li>
    <li>{{ plan.budgetitem_set.all.count }} Budget Items</li>
</ul>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-danger">
    <a href="{{ plan.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

{% block title %}
  <title>
    Delete Plan | {{ plan.description }} | {{ plan.trip.destination }} | Travel Planner
  </title>
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'trips' %}">Trips</a></li>
    <li class="breadcrumb-item"><a href="{{ plan.trip.get_absolute_url }}">{{ plan.trip.destination }}</a></li>
    <li class="breadcrumb-item"><a href="{{ plan.get_absolute_url }}">{{ plan.description }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete Plan</li>
{% endblock %}

Planner/templates/Planner/planstatus_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Plan Status: {{ planstatus.name }}</h1>

<p>Are you sure you want to delete the plan status? The status on {{ planstatus.plan_set.all.count }} plans will be set to None.</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-danger">
    <a href="{{ planstatus.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

{% block title %}
  <title>
    Delete Plan Type | {{ planstatus.name }} | Settings | Travel Planner
  </title>
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'settings' %}">Settings</a></li>
    <li class="breadcrumb-item"><a href="{% url 'planstatuses' %}">Plan Statuses</a></li>
    <li class="breadcrumb-item"><a href="{% url 'planstatus-update' planstatus.id %}">{{ planstatus.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete Plan Status</li>
{% endblock %}

Planner/templates/Planner/plantype_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Plan Type: {{ plantype.name }}</h1>

<p>Are you sure you want to delete the plan type? The type on {{ plantype.plan_set.all.count }} plans will be set to None.</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-danger">
    <a href="{{ plantype.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

{% block title %}
  <title>
    Delete Plan Type | {{ plantype.name }} | Settings | Travel Planner
  </title>
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'settings' %}">Settings</a></li>
    <li class="breadcrumb-item"><a href="{% url 'plantypes' %}">Plan Types</a></li>
    <li class="breadcrumb-item"><a href="{% url 'plantype-update' plantype.id %}">{{ plantype.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete Plan Type</li>
{% endblock %}

Planner/templates/Planner/trip_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Trip: {{ trip }}</h1>

<p>Are you sure you want to delete the trip? The following will also be deleted:</p>

<ul>
    <li>{{ trip.plan_set.all.count }} Plans</li>
    <li>{{ trip.todo_set.all.count }} Todos</li>
    <li>{{ trip.budgetitem_set.all.count }} Budget Items</li>
</ul>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-danger">
    <a href="{{ trip.get_absolute_url }}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

{% block title %}
  <title>
    Delete Trip | {{ trip.destination }} | Travel Planner
  </title>
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'trips' %}">Trips</a></li>
    <li class="breadcrumb-item"><a href="{{ trip.get_absolute_url }}">{{ trip.destination }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Delete Trip</li>
{% endblock %}

Planner/templates/Planner/trip_detail.html
{% extends "base_generic.html" %}

{% load humanize %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'trips' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ trip.destination }}</li>
{% endblock %}

{% block content %}
  <h1>Destination: {{ trip.destination }}</h1>
    <p><strong>Goal Date:</strong> {{ trip.goal_date }}</p>
    <p><strong>Completed Date:</strong> {{ trip.completed_date }}</p>
    <p><strong>Notes:</strong> {{ trip.notes }}</p>
    <p><strong>Budget:</strong>
        {% if budget.total == None %}
        $0.00
        {% else %}
        ${{ budget.total|floatformat:2|intcomma }}
        {% endif %}
        (
        {% if budget_expended.total == None %}
        $0.00
        {% else %}
        ${{ budget_expended.total|floatformat:2|intcomma }}
        {% endif %}
        expended )</p>

    <h2>Plans</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Description</th>
                <th>Notes</th>
                <th>Type</th>
                <th>Status</th>
                <th>Scheduled Start</th>
                <th>Scheduled End</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for plan in trip.plan_set.all %}
            <tr>
                <td>
                    <a href="{{ plan.get_absolute_url }}">{{ plan.description }}</a>
                </td>
                <td>
                    {{ plan.notes }}
                </td>
                <td>
                    {{ plan.type }}
                </td>
                <td>
                    {{ plan.status }}
                </td>
                <td>
                    {{ plan.scheduled_start_date_time }}
                </td>
                <td>
                    {{ plan.scheduled_end_date_time }}
                </td>
                <td>
                    <a href="{% url 'plan-update' pk=plan.id %}" class="btn btn-primary">Edit</a>
                </td>
            </tr>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <tr>
                <td>{{ planform.description }}</td>
                <td>{{ planform.notes }}</td>
                <td>{{ planform.type }}</td>
                <td>{{ planform.status }}</td>
                <td>{{ planform.scheduled_start_date_time }}</td>
                <td>{{ planform.scheduled_end_date_time }}</td>
                <td><input type="submit" value="Add" class="btn btn-primary"> {{ planform.trip.as_hidden }}<input type="hidden" name="addtype" value="plan"></td>
            </tr>
        </form>
        </tbody>
    </table>

    <h2>Todos</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Description</th>
                <th>Notes</th>
                <th>Due Date</th>
                <th>Associated Plan</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for todo in trip.todo_set.all %}
            <tr id="todo-{{ todo.id }}">
                <td>
                    {{ todo.description }}
                </td>
                <td>
                    {{ todo.notes }}
                </td>
                <td>
                    {% if todo.date_completed %}
                    Completed {{ todo.date_completed }}
                    {% else %}
                    {{ todo.due_date }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ todo.plan.get_absolute_url }}">{{ todo.plan.description }}</a>
                </td>
                <td>
                    <a href="{% url 'todo-update' pk=todo.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'todo-delete' pk=todo.id %}" class="btn btn-danger">Delete</a>
                    {% if not todo.date_completed %}
                    <form action="" method="post" class="d-inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="completetodo" value="{{ todo.id }}">
                        <input type="submit" value="Done" class="btn btn-primary">
                    </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <tr>
                <td>{{ todoform.description }}</td>
                <td>{{ todoform.notes }}</td>
                <td>{{ todoform.due_date }}</td>
                <td>{{ todoform.plan }}</td>
                <td><input type="submit" value="Add" class="btn btn-primary"> {{ todoform.trip.as_hidden }}<input type="hidden" name="addtype" value="todo"></td>
            </tr>
        </form>
        </tbody>
    </table>

    <h2>Budget</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Description</th>
                <th>Notes</th>
                <th>Type</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>Associated Plan</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for budgetitem in trip.budgetitem_set.all %}
            <tr id="budget-item-{{ budgetitem.id }}">
                <td>
                    {{ budgetitem.description }}
                </td>
                <td>
                    {{ budgetitem.notes }}
                </td>
                <td>
                    {{ budgetitem.get_type_display }}
                </td>
                <td>
                    {{ budgetitem.due_date }}
                </td>
                <td>
                    ${{ budgetitem.amount|floatformat:2|intcomma }}
                </td>
                <td>
                    <a href="{{ budgetitem.plan.get_absolute_url }}">{{ budgetitem.plan.description }}</a>
                </td>
                <td>
                    <a href="{% url 'budgetitem-update' pk=budgetitem.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'budgetitem-delete' pk=budgetitem.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <tr>
                <td>{{ budgetitemform.description }}</td>
                <td>{{ budgetitemform.notes }}</td>
                <td>{{ budgetitemform.type }}</td>
                <td>{{ budgetitemform.due_date }}</td>
                <td>{{ budgetitemform.amount }}</td>
                <td>{{ budgetitemform.plan }}</td>
                <td><input type="submit" value="Add" class="btn btn-primary"> {{ budgetitemform.trip.as_hidden }}<input type="hidden" name="addtype" value="budgetitem"></td>
            </tr>
        </form>
        </tbody>
    </table>

{% endblock %}

{% block title %}
  <title>{{ trip.destination }} | Travel Planner</title>
{% endblock %}
{% block sidebar %}
  {{ block.super }}

  <h2 class="fs-5">Trip Actions</h2>
  <ul class="sidebar-nav">
    <li><a href="{% url 'trip-update' trip.id %}">Update trip</a></li>
    <li><a href="{% url 'trip-delete' trip.id %}">Delete trip</a></li>
  </ul>

{% endblock %}